x-common-variables: &common-variables
  RESTART_ON_FAILURE: true
services:
  demo-config:
    image: registry:5000/2022mt12119/demo-config:0.0.1-SNAPSHOT
    environment: *common-variables
    volumes:
      - tmp_volume:/tmp_volume
  demo-app:
    image: registry:5000/2022mt12119/demo-app:0.0.1-SNAPSHOT
    environment: *common-variables
    volumes:
      - tmp_volume:/tmp_volume
    depends_on:
      demo-config:
        condition: service_started
    ports:
      - "8081:8080"
volumes:
  tmp_volume:
